# Generated by Django 3.2.19 on 2023-06-15 05:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Значение')),
                ('currency', models.CharField(max_length=3, verbose_name='Код валюты')),
            ],
            options={
                'verbose_name': 'цены',
                'verbose_name_plural': 'Цены',
                'ordering': ('currency', 'value'),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа')),
                ('description', models.TextField(verbose_name='Описание типа товаров')),
            ],
            options={
                'verbose_name': 'тип товара',
                'verbose_name_plural': 'Типы товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название товара')),
                ('quantity', models.IntegerField(verbose_name='Количество товара, шт.')),
                ('barcode', models.ImageField(blank=True, upload_to='images/', verbose_name='Штрихкод')),
                ('barcode_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12)], verbose_name='Штрихкод')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.price', verbose_name='Цена товара')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.type', verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'товары',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('value', 'currency'), name='unique price'),
        ),
    ]
